# Forward Kinematics: Mantis Robot

In [7]:
import modern_robotics as mr
import numpy as np

## Home position matrix

In [8]:
M = np.array([[1,0,0,0],[0,1,0,660.35],[0,0,1,0],[0,0,0,1]])
print("M = \n",M, "\n")

M = 
 [[1.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 660.350]
 [0.000 0.000 1.000 0.000]
 [0.000 0.000 0.000 1.000]] 



## Screw axis

In [9]:
q1 = np.array([0, 0, 0])
s1 = np.array([0, 1, 0])
S1 = mr.ScrewToAxis(q1, s1, 0)
print("S1 axis: \n", S1, "\n")

q2 = np.array([0, 173.5, 0])
s2 = np.array([1, 0, 0])
S2 = mr.ScrewToAxis(q2, s2, 0)
print("S2 axis: \n", S2, "\n")

q3 = np.array([0, 398.5, 0])
s3 = np.array([1, 0, 0])
S3 = mr.ScrewToAxis(q3, s3, 0)
print("S3 axis: \n", S3, "\n")

q4 = np.array([0, 428, 0])
s4 = np.array([0, 1, 0])
S4 = mr.ScrewToAxis(q4, s4, 0)
print("S4 axis: \n", S4, "\n")

q5 = np.array([0, 628.85, 0])
s5 = np.array([1, 0, 0])
S5 = mr.ScrewToAxis(q5, s5, 0)
print("S5 axis: \n", S5, "\n")

q6 = np.array([0, 660.25, 0])
s6 = np.array([0, 1, 0])
S6 = mr.ScrewToAxis(q6, s6, 0)
print("S6 axis: \n", S6[0:6], "\n")

S1 axis: 
 [0 1 0 0 0 0] 

S2 axis: 
 [1.000 0.000 0.000 0.000 0.000 -173.500] 

S3 axis: 
 [1.000 0.000 0.000 0.000 0.000 -398.500] 

S4 axis: 
 [0 1 0 0 0 0] 

S5 axis: 
 [1.000 0.000 0.000 0.000 0.000 -628.850] 

S6 axis: 
 [0.000 1.000 0.000 0.000 0.000 0.000] 



## Screw Axis list

In [10]:
Slist = np.array([S1,S2,S3,S4,S5,S6]).transpose()

## Joint rotations

In [13]:
thetalist1 = np.array([-np.pi/2, np.pi/2, np.pi/3, -np.pi/4, 1, np.pi/6])
thetalist2 = np.array([0, 0, 0, 0, 0, 0])
thetalist3 = np.array([-np.pi/2, np.pi/2, np.pi/3, -np.pi/4, 1, np.pi/6])
thetalist4 = np.array([np.pi/2, 0, 0, 0, 0, 0])
thetalist5 = np.array([0, 0, np.pi/2, 0, -np.pi/2, 0])

## Homonegeous Transformation

In [14]:
Ts = mr.FKinSpace(M,Slist, thetalist5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print("Ts = \n",Ts, "\n")

Ts = 
 [[1.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 430.000]
 [0.000 0.000 1.000 230.350]
 [0.000 0.000 0.000 1.000]] 

